### ISSUE TITLE
Invalid URL port: "-1"

### ISSUE THREAD

**Issue by shoucandanghehe** [ShiinaKin/halo-plugin-typecho#6]
```
halo      | 2025-02-20T04:10:52.918+08:00 ERROR 7 --- [      Thread-11] i.s.h.t.controller.TypechoController     : unexpected exception handled
halo      | 
halo      | java.lang.IllegalArgumentException: Invalid URL port: "-1"
halo      |     at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1330) ~[na:na]
halo      |     at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1634) ~[na:na]
halo      |     at okhttp3.Request$Builder.url(Request.kt:184) ~[na:na]
halo      |     at io.sakurasou.halo.typecho.util.HttpUtils.sendGetReq(HttpUtils.kt:34) ~[na:na]
halo      |     at io.sakurasou.halo.typecho.service.UploadServiceImpl.handleListTagsOrCategories(UploadServiceImpl.kt:175) ~[na:na]
halo      |     at io.sakurasou.halo.typecho.service.UploadServiceImpl.handleListTags(UploadServiceImpl.kt:171) ~[na:na]
halo      |     at io.sakurasou.halo.typecho.service.UploadServiceImpl.handlePosts(UploadServiceImpl.kt:76) ~[na:na]
halo      |     at io.sakurasou.halo.typecho.controller.TypechoController.uploadTypechoFile$lambda$3(TypechoController.kt:53) ~[na:na]
halo      |     at io.sakurasou.halo.typecho.controller.TypechoController.uploadTypechoFile$lambda$4(TypechoController.kt:47) ~[na:na]
halo      |     at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106) ~[reactor-core-3.7.2.jar:3.7.2]
halo      |     at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:294) ~[reactor-core-3.7.2.jar:3.7.2]
halo      |     at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:188) ~[reactor-core-3.7.2.jar:3.7.2]
halo      |     at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:237) ~[reactor-core-3.7.2.jar:3.7.2]
halo      |     at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:204) ~[reactor-core-3.7.2.jar:3.7.2]
halo      |     at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:250) ~[reactor-core-3.7.2.jar:3.7.2]
halo      |     at reactor.core.publisher.MonoFlatMap$FlatMapInner.onComplete(MonoFlatMap.java:324) ~[reactor-core-3.7.2.jar:3.7.2]
halo      |     at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:144) ~[reactor-core-3.7.2.jar:3.7.2]
halo      |     at reactor.core.publisher.LambdaSubscriber.onComplete(LambdaSubscriber.java:132) ~[reactor-core-3.7.2.jar:3.7.2]
halo      |     at reactor.core.publisher.FluxCreate$BaseSink.complete(FluxCreate.java:465) ~[reactor-core-3.7.2.jar:3.7.2]
halo      |     at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:871) ~[reactor-core-3.7.2.jar:3.7.2]
halo      |     at reactor.core.publisher.FluxCreate$BufferAsyncSink.complete(FluxCreate.java:819) ~[reactor-core-3.7.2.jar:3.7.2]
halo      |     at reactor.core.publisher.FluxCreate$SerializedFluxSink.drainLoop(FluxCreate.java:249) ~[reactor-core-3.7.2.jar:3.7.2]
halo      |     at reactor.core.publisher.FluxCreate$SerializedFluxSink.drain(FluxCreate.java:215) ~[reactor-core-3.7.2.jar:3.7.2]
halo      |     at reactor.core.publisher.FluxCreate$SerializedFluxSink.complete(FluxCreate.java:206) ~[reactor-core-3.7.2.jar:3.7.2]
halo      |     at org.springframework.core.io.buffer.DataBufferUtils$WriteCompletionHandler.completed(DataBufferUtils.java:1260) ~[spring-core-6.2.2.jar:6.2.2]
halo      |     at org.springframework.core.io.buffer.DataBufferUtils$WriteCompletionHandler.completed(DataBufferUtils.java:1178) ~[spring-core-6.2.2.jar:6.2.2]
halo      |     at java.base/sun.nio.ch.Invoker.invokeUnchecked(Unknown Source) ~[na:na]
halo      |     at java.base/sun.nio.ch.SimpleAsynchronousFileChannelImpl$3.run(Unknown Source) ~[na:na]
halo      |     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
halo      |     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
halo      |     at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
halo      | 
halo      | 2025-02-20T04:10:52.943+08:00  INFO 7 --- [      Thread-11] i.s.h.t.controller.TypechoController     : unzTemp file deleted: true
```

```
services:
  halo:
    image: registry.fit2cloud.com/halo/halo:2.20
    container_name: halo
    restart: on-failure:3
    depends_on:
      halodb:
        condition: service_healthy
    networks:
      halo_network:
      caddy_network:
    ports:
      - "8090:8090"
    volumes:
      - halo_data:/root/.halo2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health/readiness"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      - JVM_OPTS=-Xmx256m -Xms256m
    command:
      - --spring.r2dbc.url=r2dbc:pool:postgresql://halodb/halo
      - --spring.r2dbc.username=
      - --spring.r2dbc.password=
      - --spring.sql.init.platform=postgresql
      - --halo.external-url=https://blog.xxx.com/

  halodb:
    image: postgres:15.4
    restart: on-failure:3
    networks:
      halo_network:
    volumes:
      - halo_db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=
      - POSTGRES_DB=
      - PGUSER=

networks:
  halo_network:
  caddy_network:
    external: true

volumes:
  halo_data:
  halo_db:
```
